// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TiendaPc.DLL.Models;

public partial class Ciudad
{
    public int IdCiudad { get; set; }

    public string NombreCiudad { get; set; }

    public int IdProvincia { get; set; }

    [JsonIgnore]
    public virtual ICollection<Barrio> Barrios { get; set; } = new List<Barrio>();
    [JsonIgnore]

    public virtual Provincia IdProvinciaNavigation { get; set; }
}