// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaPc.DLL.Models;

public partial class Empleado
{
    public int LegajoEmp { get; set; }

    public int IdBarrio { get; set; }

    public int IdRol { get; set; }

    public int IdTipoDoc { get; set; }

    public string Documento { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Direccion { get; set; }

    public int NroCalle { get; set; }

    public string Pass { get; set; }

    public bool? Estado { get; set; }

    public virtual ICollection<Contacto> Contactos { get; set; } = new List<Contacto>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual RolEmpleado IdRolNavigation { get; set; }

    public virtual TipoDocumento IdTipoDocNavigation { get; set; }

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}