// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TiendaPc.DLL.Models;

public partial class Especificacion
{
    public int IdEspec { get; set; }

    public string NombreEspecificacion { get; set; }

    [JsonIgnore]
    public virtual ICollection<EspecificacionComponente> EspecificacionesComponentes { get; set; } = new List<EspecificacionComponente>();
    [JsonIgnore]
    public virtual ICollection<TipoComponenteEspecificacion> TiposComponentesEspecificaciones { get; set; } = new List<TipoComponenteEspecificacion>();
}