// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TiendaPc.DLL.Models;

public partial class FormaPago
{
    public int IdFormaPago { get; set; }

    public string NombreFormaPago { get; set; }

    public decimal? Recargo { get; set; }

    public decimal? Descuento { get; set; }

    [JsonIgnore]
    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();


    //public virtual ICollection<PedidoFormaPago> PedidosFormasPagos { get; set; } = new List<PedidoFormaPago>();
}