// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TiendaPc.DLL.Models;

public partial class Pedido
{
    public int IdPedido { get; set; }

    public int IdCliente { get; set; }

    public int IdFormaPago { get; set; }

    public int? IdCategoriaFiscal { get; set; }

    public int? LegajoEmp { get; set; }

    public bool ArmadoPc { get; set; }

    public decimal? PrecioArmadoPc { get; set; }

    public DateTime FechaPedido { get; set; }

    public int IdFormaEntrega { get; set; }

    public string Estado { get; set; }

    public DateTime? FechaCancelacion { get; set; }

    public string MotivoCancelacion { get; set; }

    public virtual ICollection<DetallePedido> DetallesPedidos { get; set; } = new List<DetallePedido>();
    [JsonIgnore]
    public virtual CategoriaFiscal IdCategoriaFiscalNavigation { get; set; }

    [JsonIgnore]
    public virtual FormaPago IdFormaPagoNavigation { get; set; }
    [JsonIgnore]
    public virtual Cliente IdClienteNavigation { get; set; }
    [JsonIgnore]
    public virtual FormaEntrega IdFormaEntregaNavigation { get; set; }
    [JsonIgnore]
    public virtual Empleado LegajoEmpNavigation { get; set; }

}