// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaPc.DLL.Models;

public partial class PedidoFormaPago
{
    public int IdPedFor { get; set; }

    public int? IdPedido { get; set; }

    public int? IdFormaPago { get; set; }

    public decimal? Porcentaje { get; set; }

    public virtual FormaPago IdFormaPagoNavigation { get; set; }

    public virtual Pedido IdPedidoNavigation { get; set; }
}