// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TiendaPc.DLL.Models;

public partial class Provincia
{
    public int IdProvincia { get; set; }

    public string NombreProvincia { get; set; }

    [JsonIgnore]
    public virtual ICollection<Ciudad> Ciudades { get; set; } = new List<Ciudad>();
}