// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaPc.DLL.Models;

public partial class RolEmpleado
{
    public int IdRol { get; set; }

    public string Rol { get; set; }

    public string DescRol { get; set; }

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();
}