// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TiendaPc.DLL.Models;

public partial class TipoComponenteEspecificacion
{
    public int IdTipoEspec { get; set; }

    public int? IdTipoComponente { get; set; }

    public int? IdEspec { get; set; }

    public virtual Especificacion IdEspecNavigation { get; set; }

    public virtual TipoComponente IdTipoComponenteNavigation { get; set; }
}