// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace TiendaPc.DLL.Models
{
    public class EmpleadoDto
    {
        public int LegajoEmp { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public int NroCalle { get; set; }
        public string Documento { get; set; }
        public string RolNombre { get; set; }    // Nombre del rol
        public bool? Estado { get; set; }
    }
}
